# @package _global_

defaults:
  - amp_mlp_beta
  - /env/getup

env:
  config:
    state_init: Hybrid
    hybrid_init_prob: 0.5

agent:
  config:
    task_reward_w: 0.5
    num_mini_epochs: 8

    modules:
      real_self_obs:
        _target_: protomotions.agents.common.common.Flatten
        num_in: ${env.config.getup_params.obs_size}
        num_out: ${.num_in}
        config:
          obs_key: real_self_obs
          normalize_obs: true
          norm_clamp_value: 5

    # Append the direction obs to the actor and critic inputs
    model:
      config: 
        actor:
          config:
            mu_model:
              config:
                input_models:
                  real_self_obs: ${agent.config.modules.real_self_obs}

    extra_inputs:
      real_self_obs: true
