# @package _global_

defaults:
  - base_env

# Env structure
env:
  _target_: protomotions.envs.getup.env.Getup
  config:
    enable_height_termination: False
    getup_params:
      obs_size: 75
      penalize_contact_indices: [0, 1, 2, 4, 5, 6, 9, 10, 11, 14, 15, 16, 22, 23]
      # Trunk, H1, H2, AL1, AL2, AL3, AR1, AR2, AR3, Waist, Hip_Pitch_Left, Hip_Roll_Left, Hip_Yaw_Left, Shank_Left, Ankle_Cross_Left,

# Globally accessible parameters
